mongodb:
  image: mongo:4.4.2
  container_name: mongo-slpdb-testnet
  ports:
    #- "3608:27017"
    - "172.17.0.1:13301:27017"
  volumes:
    - ../data/mongodb:/data/db
  command: mongod --logpath=/dev/null # -- quiet
  restart: always

slpdb:
  build: .
  dockerfile: Dockerfile
  #image: christroutner/slpdb-testnet_slpdb:0.15.3
  #image: slpdb-testnet_slpdb
  container_name: slpdb-testnet
  links:
    - mongodb
#  ports:
#    - "3003:3000"
#    - "9229:9229"
  volumes:
    - ../data/leveldb:/home/safeuser/SLPDB/_leveldb_testnet
    - ../config:/home/safeuser/config
  restart: always

slpserve:
  build: ./slpserve/
  dockerfile: Dockerfile
  #image: christroutner/slpdb-testnet_slpserve:latest
  container_name: slpserve-testnet
  links:
    - mongodb
  ports:
    - "13300:4000"
  restart: always
